export default {
  locale: 'en',

  tasks: 'Tasks',
  newTask: 'New Task',
  complete: 'Complete',
  undo: 'Undo',
  unsaved: 'unsaved',
  edit: 'Edit',
  delete: 'Delete',
  yes: 'Yes',
  no: 'No',
  completeFirstTitle: 'You completed your first task!', 
  completeFirstText: 'Go to the reward page to create and redeem rewards.\nBy default, completed tasks will be automatically hidden after a period of time.\nLong press the coin icon in the upper right corner to quickly switch whether to display the completed task.',
  taskDeleteTitle: 'Are you sure to delete this task?',
  taskDeleteText: 'It does not affect the coin record and amount of coins.\nThis operation CANNOT be undone.',
  clearContentTitle: 'Clear Unsaved Content',
  clearContentText: 'Are you sure you want to discard unsaved content?',

  editTask: 'Edit Task',
  taskName: 'Task Name',
  description: 'Description',
  subtasks: 'Subtasks',
  optional: 'optional',
  setDeadline: 'Set Deadline',
  deadline: 'Deadline',
  setStartingTime: 'Set Starting Time',
  startingTime: 'Starting Time',
  comfirmStart: 'Request Confirmation Before Starting',
  comfirmStartAlert: 'Once enabled, you must enter the application and confirm the start before the starting time, otherwise it will be considered a timeout.',
  invalidProperty: 'Invalid Property',
  startingTimeLate: 'The starting time cannot be later than the deadline.',
  deadlineEarly: 'The deadline cannot be earlier than now.',
  repeats: 'Repeats',
  until: 'until',
  reminders: 'Reminders',
  timeMark: 'After setting the deadline or enable comfirm before starting time, you need to enter the program before the deadline or starting time to mark the task as complete or started.',
  bonusCoins: 'Bonus Coin(s)',
  enableDeduct: 'Deducting Coin(s) When Failed',
  deductingCoins: 'Deducting Coin(s)',
  coinsMark: 'When you complete the task, you will receive the bonus coins you set and use them to redeem the rewards you set.',
  add: 'Add',
  close: 'Close',
  save: 'Save',

  chooseColor: 'CHOOSE A COLOR',
  chooseIcon: 'CHOOSE A ICON',
  done: 'Done',

  subtasksHolder: 'Enter subtasks here, one per line...\neg.\nSubtask 1\nSubtask 2',
  subtasksMark: 'You can refine your tasks into multiple subtasks.  When you mark all subtasks as complete, the main task will also be marked as complete, and vice versa. However, marking the status of the subtask does not affect the status of the main task after the main task is completed or expired.',

  basedOnDeadline: 'BASED ON DEADLINE',
  basedOnStartingTime: 'BASED ON STARTTIME',
  beforeDeadline: '!time! before the deadline',
  beforeStartingTime: '!time! before the starting time',
  minutes: 'minutes',
  hour: 'hour',
  day: 'day',
  atStartingTime: 'At the starting time',
  customTime: 'Custom time',
  customTimeMark: 'The custom time unit is minutes.\nYour device operating system will push notifications to you at the reminder time of your choice, without the need for a network. But do not rely reminders, because local plan reminders are unstable and sometimes may fail to send or repeat for unforeseen reasons.\nSince we do not have a background service, if you set end of repeats, you must open Pamphlet once after the end of the repeat or the reminder repeat will not stop.',

  repeatTypes: 'REPEAT TYPES',
  repeatEnd: 'REPEAT END',
  none: 'None',
  daily: 'Daily',
  weekly: 'Weekly',
  weeklyMark: ' (!day! of each week)',
  weekdays: 'Weekdays',
  weekdaysMark: ' (Mondays to Fridays)',
  weekends: 'Weekends',
  weekendsMark: ' (Sundays and Saturdays)',
  monthly: 'Monthly',
  monthlyMark: ' (!date! of each month)',
  yearly: 'Yearly',
  yearlyMark: ' (!date! of each year)',
  wDay0: 'Sunday',
  wDay1: 'Monday',
  wDay2: 'Tuesday',
  wDay3: 'Wednesday',
  wDay4: 'Thursday',
  wDay5: 'Friday',
  wDay6: 'Saturday',
  setEndOfRepeats: 'Set End Of Repeats',
  repeatUntil: 'Repeat Until',

  rewards: 'Rewards',
  newReward: 'New Reward',
  redeem: 'Redeem',
  redeemTitle: 'Redeem',
  redeemText: 'Are you sure to redeem this reward?\nIt will take you !price! coin(s) and you own !coin! coin(s) now.',
  redeemNoEnoughCoin: 'You do not have enough coin to redeem it.\nIt will take you !price! coin(s) but you only own !coin! coin(s) now.\nComplete some tasks before you redeem it!',
  redeemFirstTitle: 'You redeemed your first reward!', 
  redeemFirstText: 'Complete more tasks to redeem more rewards.\nPress the coin icon in the top right corner to view the completed coin record.\nLong press the coin icon in the upper right corner of the task page to quickly switch whether to display the completed task.',
  rewardDeleteTitle: 'Are you sure to delete this reward?',
  rewardDeleteText: 'It does not affect the coin record and amount of coins.\nThis operation CANNOT be undone.',

  editReward: 'Edit Reward',
  rewardName: 'Reward Name',
  icon: 'Icon',
  price: 'Price',
  priceMark: 'You need this amount of coins to redeem the reward.',

  records: 'Records',
  recordDeleteTitle: 'Are you sure to delete this record?',
  recordDeleteText: 'It does not affect amount of coins.\nThis operation CANNOT be undone.',

  settings: 'Settings',
  taskRelated: 'TASK RELATED',
  showSeconds: 'Show Seconds',
  taskSummary: 'Task Summary',
  strictMode: 'Strict Mode',
  auxiliaryTools: 'AUXILIARY TOOLS',
  resetApp: 'Reset App',
  reset: 'Reset',
  cancel: 'Cancel',
  rate: 'Rate Us',
  rateTitle: 'What do you think of Pamphlet?',
  rateText: 'u know...',
  rateNeutral: 'Later',
  rateNegative: 'Have some problems...',
  ratePositive: 'Not bad!',
  feedback: 'Feedback',

  sureToReset: 'Make sure to RESET THE APP?',
  sureToResetMessage: 'This is equivalent to reinstalling the Pamphlet. All data for this app (including all tasks and rewards) WILL BE DELETED and CANNOT be retrieved!',
  // sureToResetMessage: 'This is equivalent to reinstalling Pamphlet. You will be logged out of Pamphlet and all local data (including local copies of all tasks and rewards) will be lost, but the data on the server will not be affected.',

  welcome: 'Welcome to Pamphlet',
  continue: 'Continue',
  feature1Title: 'Set a task deadline',
  feature1Text: 'Complete the task before the deadline, otherwise the corresponding number of coins will be deducted.',
  feature2Title: 'Link coins to real rewards',
  feature2Text: 'Set rewards for yourself and exchange them with the coins you got by completing the task on time.',
  feature3Title: 'Intuitively feel the deadline',
  feature3Text: 'You can enable show second of the remaining time in the settings, and intuitively feel the proximity of deadline.',
  privatePolicy: 'We will respect and protect your privacy.',
  viewPrivatePolicy: 'View our Privacy Policy',

  // Ext.1
  asec: 's',
  amin: 'min',
  ahour: 'h',
  aday: 'd',
  amonth: 'mo',
  ayear: 'y',
  start: 'Start',
  summary: 'Summary: ',
  leftToStart: '!leftTime! Left To Start',
  leftToDeadline: '!leftTime! Left To Deadline',
  startedAt: 'Started At',
  completedAt: 'Completed At',
  exceed: 'Exceed !type!',
  exceedAt: 'Exceed !type! At',
  taskFailed: 'Task "!taskName!" Failed',
  taskFailedDeadline: 'The task has failed because you did not mark the task as completed before the deadline.',
  taskFailedStartingTime: 'Since you turned on requesting comfirmation before starting, but did not mark the task as started before the starting time of the task, the task has failed.',
  enterTaskSummary: 'Fill in the task summary',
  taskDeleteRepeatsText: 'This task has turnd on repeat. \nIf you need to delete all duplicates after the day\'s task, select Edit and modify the repeat end date on the repeat page.',
  deleteForThisDay: 'Delete only this day task',
  deleteForAllDays: 'Delete all duplicates of the task',
  strictModeLockedMark: 'Since you have turned on strict mode in the settings, some items in this section are locked and cannot be edited again.',
  strictModeUnlockedMark: 'Since you have turned on strict mode in the settings, some items in this section will be locked and cannot be edited again.',
  neitherDeadlineNorStartingTime: 'At least one item must be set for the deadline and starting time.',
  closeToDeadline: '"!taskName!" Is About To Expire',
  closeToDeadlineDetail: 'There is still !leftTime! from the deadline.',
  taskStarted: '"!taskName!" Has Started',
  taskStartedDetail: 'The task started at !startingTime!.',
  closeToStartingTime: '"!taskName!" Is About To Begin',
  closeToStartingTimeDetail: 'There is still !leftTime! from the starting time.',
  taskFailureReminder: 'Task Failure Reminder',
  noNotiPermission: 'No Notification Permission',
  noNotiPermissionDetail: 'We need notification permission to send you a reminder. Go to system settings to enable it.\nWe would not push you anything other than a task reminder.',
  gotoSettings: 'Go To Settings',
  showCompletedTasks: 'Show Completed Tasks',
  showRemainingTimeRatio: 'Show Remaining Time Ratio',
  lessThanAMin: 'Less Than A Min',
  editTaskMark: 'In order to protect the data, modifying the period of the task that has expired (regardless of whether it has been completed) cannot make the status of the task that has expired become unoverdated again.',
  taskNotStarted: 'The Task Has Not Started Yet',
  taskNotStartedDetail: 'If you need to mark the subtask completion at this point, first mark the main task as started.',
  topTask: 'Top Task',
  topTaskMark: 'Once enabled, this task will appear on top of all other tasks that do not have this enabled.',
  feedbackSubject: 'Pamphlet !version! Feedback (!locale!)',
  feedbackBody: '<h3>Tell us where we can improve.</h3>\n<p>Write down your questions or suggestions here.</p>\n<br />\n<p style="font-size: 14px; color: #A0A0A0">You can fill out the email in any language, but do not modify our automatically generated English email subject, which contains the feedback version of the app and the i18n code of your language. </p>\n<p style="font-size: 14px; color: #A0A0A0">You can send us a feedback email using any email client, our email address is contact@cuso4.tech</p>',

  // Ext.2
  showUsedTimeRatio: 'Show Used Time Ratio',
  appRelated: 'APP RELATED',
  darkMode: 'Dark Mode',
  followSystemSwitch: 'Follow System Switch',
  autoSwitchMark: 'The application language always follows the system switch regardless of whether the following system is turned on.',
  taskRelatedMark: 'The remaining time ratio can only be displayed when the start time and deadline are set at the same time and the task is in progress.\nLong press the date text of the task page to switch the date to today. Long press the coin icon in the upper right corner of the task page to quickly switch whether or not to complete the task.\nThe remaining time ratio can only be displayed when the start time and deadline are set at the same time and the task is in progress.\nWhen there are unsaved tasks/rewards, long press the new task/reward button to clear unsaved tasks/rewards.',
  appRelatedMark: 'In strict mode, you will not be able to change some attributes of created tasks or rewards, including deadlines and reward prices.',
  notices3rd: 'Third-party Notices',
}