import 'moment/locale/zh-cn';

export default {
  locale: 'zh-cn',

  tasks: '任务',
  newTask: '新任务',
  complete: '完成',
  undo: '撤销',
  unsaved: '未保存',
  edit: '编辑',
  delete: '删除',
  yes: '是',
  no: '否',
  completeFirstTitle: '你完成了你的第一个任务！',
  completeFirstText: '去奖励页创建和兑换奖励吧。\n默认情况下已完成的任务将在一段时间后自动隐藏。\n长按右上角的硬币图标可以快速切换是否显示完成任务。',
  taskDeleteTitle: '确定删除这项任务吗？',
  taskDeleteText: '这不会影响已获得的硬币和硬币记录。\n这个操作不能被撤销。',
  clearContentTitle: '清空未保存的内容',
  clearContentText: '确定放弃未保存的内容？',

  editTask: '编辑任务',
  taskName: '任务名称',
  description: '描述',
  subtasks: '子任务',
  optional: '可选',
  setDeadline: '设置期限',
  deadline: '期限',
  setStartingTime: '设置开始时间',
  startingTime: '开始时间',
  comfirmStart: '在开始前要求确认',
  comfirmStartAlert: '一旦启用，你必须在开始时间之前进入 Pamphlet 并确认开始，否则将被视为超时。',
  invalidProperty: '无效的属性',
  startingTimeLate: '开始时间不能晚于期限。',
  deadlineEarly: '期限不能早于现在。',
  repeats: '重复',
  until: '直到',
  reminders: '提醒',
  timeMark: '在设置了期限或启用了在开始时间前确认后，你需要在期限或开始时间前进入程序，并将任务标记为完成或开始。',
  bonusCoins: '奖励硬币',
  enableDeduct: '在失败时扣除硬币',
  deductingCoins: '扣除硬币',
  coinsMark: '在你完成任务时，你将收到你设置的奖励硬币并且可以用它们兑换你设置的奖励。',
  add: '添加',
  close: '关闭',
  save: '保存',

  chooseColor: '选择一个颜色',
  chooseIcon: '选择一个图标',
  done: '完成',

  subtasksHolder: '在这输入你的子任务，每行一个...\neg.\n子任务 1\n子任务 2',
  subtasksMark: '你可以将你的任务细分为多个子任务。 在你将所有子任务都标记为完成时，主任务也将被标记为完成，反之亦然。但在主任务完成或超出期限后，标记子任务状态不会影响主任务状态。',

  basedOnDeadline: '基于期限',
  basedOnStartingTime: '基于开始时间',
  beforeDeadline: '在期限前 !time!',
  beforeStartingTime: '在开始时间前 !time!',
  minutes: '分钟',
  hour: '小时',
  day: '天',
  atStartingTime: '在开始时间',
  customTime: '自定义时间',
  customTimeMark: '自定义时间单位为分钟。\n你的设备操作系统将在你选择的提醒时间向你推送通知，不需要网络。但不要过度依赖提醒，本地计划的提醒不稳定，有时会由于无法预知的原因发送失败或重复发送。\n由于我们没有后台服务，如果你设置了重复的结束，你必须在重复结束后打开一次 Pamphlet 否则提醒重复将不会停止。',

  repeatTypes: '重复类型',
  repeatEnd: '结束重复',
  none: '无',
  daily: '每日',
  weekly: '每周',
  weeklyMark: ' (每周的 !day!)',
  weekdays: '工作日',
  weekdaysMark: ' (周一 到 周五)',
  weekends: '周末',
  weekendsMark: ' (周天 和 周六)',
  monthly: '每月',
  monthlyMark: ' (每月的 !date!)',
  yearly: '每年',
  yearlyMark: ' (每年的 !date!)',
  wDay0: '周日',
  wDay1: '周一',
  wDay2: '周二',
  wDay3: '周三',
  wDay4: '周四',
  wDay5: '周五',
  wDay6: '周六',
  setEndOfRepeats: '设置重复的结束',
  repeatUntil: '重复直到',

  rewards: '奖励',
  newReward: '新奖励',
  redeem: '兑换',
  redeemTitle: '兑换',
  redeemText: '确定兑换这项奖励？\n这需要 !price! 枚硬币，你现在有 !coin! 枚。',
  redeemNoEnoughCoin: '你没有足够的硬币来兑换它。\n这需要 !price! 枚硬币但你现在只有 !coin! 枚。\n在来兑换前完成更多的任务!',
  redeemFirstTitle: '你兑换了第一个奖励！',
  redeemFirstText: '完成更多的任务来兑换更多的奖励。\n按下右上角的硬币图标来查看完成的硬币记录。\n长按任务页右上角的硬币图标可以快速切换是否显示完成任务。',
  rewardDeleteTitle: '确定删除这项奖励？',
  rewardDeleteText: '这不会影响硬币记录和硬币数量。\n这个操作不能被撤销。',

  editReward: '编辑奖励',
  rewardName: '奖励名称',
  icon: '图标',
  price: '单价',
  priceMark: '你需要这数量的硬币来兑换这个奖励。',

  records: '记录',
  recordDeleteTitle: '确定删除这条记录？',
  recordDeleteText: '这不会影响硬币数量。\n这操作不能被撤销。',

  settings: '设置',
  taskRelated: '任务相关',
  showSeconds: '显示秒',
  taskSummary: '任务总结',
  strictMode: '严格模式',
  auxiliaryTools: '辅助工具',
  resetApp: '重置应用',
  reset: '重置',
  cancel: '取消',
  rate: '给我们打分',
  rateTitle: '觉得 Pamphlet 怎么样？',
  rateText: '你知道的...',
  rateNeutral: '再说',
  rateNegative: '有些问题...',
  ratePositive: '不错！',
  feedback: '反馈',

  sureToReset: '确定重置应用？',
  sureToResetMessage: '这相当于重新安装 Pamphlet。 该应用的所有数据 (包含所有任务和奖励) 都将被删除，且无法找回！',
  // sureToResetMessage: '这相当于重新安装 Pamphlet。 你将从Pamphlet 登出并且所有本地数据 (包含所有任务和奖励的本地副本) 都会丢失，但在服务器上的数据不受影响。',

  welcome: '欢迎使用 Pamphlet',
  continue: '继续',
  feature1Title: '设置任务期限',
  feature1Text: '在期限前完成任务，否则相应数量的硬币将被扣除。',
  feature2Title: '使硬币与真实奖励有关',
  feature2Text: '自行设置奖励并用按时完成任务获得的硬币兑换它们。',
  feature3Title: '直观地感受期限',
  feature3Text: '你可以在设置中启用显示剩余时间的秒，并直观地感受期限靠近。',
  privatePolicy: '我们将尊重和保护你的隐私。',
  viewPrivatePolicy: '查看我们的隐私政策',

  // Ext.1
  asec: '秒',
  amin: '分',
  ahour: '时',
  aday: '天',
  amonth: '月',
  ayear: '年',
  start: '开始',
  summary: '总结：',
  leftToStart: '距离开始还有 !leftTime!',
  leftToDeadline: '距离期限还有 !leftTime!',
  startedAt: '开始于',
  completedAt: '完成于',
  exceed: '超出 !type!',
  exceedAt: '超出 !type! 于',
  taskFailed: '任务 “!taskName!” 失败',
  taskFailedDeadline: '由于你没有在任务的期限之前将任务标记为完成，任务已失败。',
  taskFailedStartingTime: '由于你开启了在开始前要求确认，但没有在任务的开始时间之前将任务标记为开始，任务已失败。',
  enterTaskSummary: '填写任务总结',
  taskDeleteRepeatsText: '此任务已开启重复。\n如果需要删除该日任务之后的所有重复，选择编辑并在重复页修改重复结束日期。',
  deleteForThisDay: '仅删除单日任务',
  deleteForAllDays: '删除任务的全部重复',
  strictModeLockedMark: '你已在设置中开启了严格模式，这个部分的一些项目被锁定并不能再次编辑。',
  strictModeUnlockedMark: '你已在设置中开启了严格模式，这个部分的一些项目在保存后将被锁定并不能再次编辑。',
  neitherDeadlineNorStartingTime: '期限和开始时间至少需要设置一项。',
  closeToDeadline: '"!taskName!" 即将超时',
  closeToDeadlineDetail: '离期限还有 !leftTime!。',
  taskStarted: '"!taskName!" 已经开始',
  taskStartedDetail: '该任务开始于 !startingTime!。',
  closeToStartingTime: '"!taskName!" 即将开始',
  closeToStartingTimeDetail: '离开始时间还有 !leftTime!。',
  taskFailureReminder: '任务失败提醒',
  noNotiPermission: '没有通知权限',
  noNotiPermissionDetail: '我们需要通知权限来给你发送提醒。去系统设置中开启。\n我们不会给你推送除了任务提醒以外的任何内容。',
  gotoSettings: '前往设置',
  showCompletedTasks: '显示已完成的任务',
  showRemainingTimeRatio: '显示剩余时间占比',
  lessThanAMin: '少于一分钟',
  editTaskMark: '为了保护数据，修改已超期的任务（不管是否已完成）的期限不能使已超期的任务状态重新变为未超期。',
  taskNotStarted: '任务还未开始',
  taskNotStartedDetail: '如果你此时需要标记子任务完成，先将主任务标记为开始。',
  topTask: '置顶任务',
  topTaskMark: '启用后此任务将显示在其它所有未启用此项的任务之上。',
  feedbackSubject: 'Pamphlet !version! Feedback (!locale!)',
  feedbackBody: '<h3>告诉我们哪里还可以提升。</h3>\n<p>在这里写下你遇到的问题或者建议。</p>\n<br />\n<p style="font-size: 14px; color: #A0A0A0">你可以使用任何语言填写邮件，但不要修改我们自动生成的英文邮件主题，里面包含了反馈的应用版本和你使用的语言的国际化代码。</p>\n<p style="font-size: 14px; color: #A0A0A0">你可以使用任何邮箱客户端给我们发送反馈邮件，我们的邮箱是 contact@cuso4.tech</p>',

  // Ext.2
  showUsedTimeRatio: '显示已用时间占比',
  appRelated: '应用相关',
  darkMode: '暗色模式',
  followSystemSwitch: '跟随系统变化',
  autoSwitchMark: '无论是否开启跟随系统，应用的语言总是跟随系统变化。',
  taskRelatedMark: '剩余时间占比只有在同时设置开始时间和期限，并且任务正在进行时才能被显示。\n长按任务页的日期文字可以切换日期到今天。长按任务页右上角的硬币图标可以快速切换是否显示完成任务。\n有未保存任务/奖励的时，长按新任务/奖励按钮可清空未保存任务/奖励。',
  appRelatedMark: '在严格模式下，你将不能修改一些已创建任务和奖励的属性，包括期限和奖励单价。',
  notices3rd: '第三方公告',
}